<a href="https://colab.research.google.com/github/santoshtiwari41/Numpy-basic-to-advanced/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
#Basic to Advanced Numpy

# Importing Numpy
import numpy as np

In [5]:
#Creating Arrays
# 1D Array
array_1d = np.array([1, 2, 3, 4])
print(array_1d)


[1 2 3 4]


In [4]:
# 2D Array
array_2d = np.array([[1, 2], [3, 4]])
print(array_2d)
array_2d


[[1 2]
 [3 4]]


array([[1, 2],
       [3, 4]])

In [6]:
# Array Attributes
print(array_2d.shape)  # Shape of the array
print(array_2d.ndim)   # Number of dimensions
print(array_2d.size)   # Total number of elements
print(array_2d.dtype)  # Data type of elements

(2, 2)
2
4
int64


In [19]:
# Array Initialization
zeros = np.zeros((2, 3))  # 2x3 array of zeros
ones = np.ones((3, 3))    # 3x3 array of ones
full = np.full((2, 2), 7) # 2x2 array filled with 7
identity = np.eye(3)      # 3x3 Identity matrix
arange = np.arange(0, 10, 2) # Array from 0 to 10 with step 2
linspace = np.linspace(0, 1, 5) # 5 equally spaced points from 0 to 1
print('\n 2x3 array of zeros \n',zeros)
print('\n 3x3 array of ones\n',ones)
print('\n 2x2 array filled with 7\n',full)
print('\n 3x3 Identity matrix\n',identity)
print('\n Array from 0 to 10 with step 2\n',arange)
print('\n 5 equally spaced points from 0 to 1\n',linspace)



 2x3 array of zeros 
 [[0. 0. 0.]
 [0. 0. 0.]]

 3x3 array of ones
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

 2x2 array filled with 7
 [[7 7]
 [7 7]]

 3x3 Identity matrix
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

 Array from 0 to 10 with step 2
 [0 2 4 6 8]

 5 equally spaced points from 0 to 1
 [0.   0.25 0.5  0.75 1.  ]


In [23]:
# Random Arrays
random_uniform = np.random.rand(2, 3)  # Random values in [0, 1)
random_normal = np.random.randn(2, 3)  # Random values from normal distribution
random_int = np.random.randint(0, 10, (2, 2))  # Random integers in [0, 10)
print('\n Random values in [0, 1) \n',random_uniform)
print('\n Random values from normal distribution \n ',random_normal)
print('\n Random integers in [0, 10) \n ',random_int)


 Random values in [0, 1) 
 [[0.38794305 0.40898888 0.41813967]
 [0.94469189 0.94397193 0.01225869]]

 Random values from normal distribution 
  [[ 1.92679082  1.1523416  -0.41684816]
 [-1.87744047 -0.68714032 -0.59717432]]

 Random integers in [0, 10) 
  [[1 9]
 [1 8]]


In [26]:
# Reshaping Arrays
print('\n above 1d array \n ',array_1d)
reshaped = np.reshape(array_1d, (2, 2))  # Reshape to 2x2
flattened = array_2d.flatten()  # Flatten 2D to 1D
print('\n reshape to 2x2 \n ',reshaped)
print('\n flatten 2d to 1d \n',flattened)


 above 1d array 
  [1 2 3 4]

 reshape to 2x2 
  [[1 2]
 [3 4]]

 flatten 2d to 1d 
 [1 2 3 4]
