<a href="https://colab.research.google.com/github/santoshtiwari41/Numpy-basic-to-advanced/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
#Basic to Advanced Numpy

# Importing Numpy
import numpy as np

In [5]:
#Creating Arrays
# 1D Array
array_1d = np.array([1, 2, 3, 4])
print(array_1d)


[1 2 3 4]


In [4]:
# 2D Array
array_2d = np.array([[1, 2], [3, 4]])
print(array_2d)
array_2d


[[1 2]
 [3 4]]


array([[1, 2],
       [3, 4]])

In [6]:
# Array Attributes
print(array_2d.shape)  # Shape of the array
print(array_2d.ndim)   # Number of dimensions
print(array_2d.size)   # Total number of elements
print(array_2d.dtype)  # Data type of elements

(2, 2)
2
4
int64


In [19]:
# Array Initialization
zeros = np.zeros((2, 3))  # 2x3 array of zeros
ones = np.ones((3, 3))    # 3x3 array of ones
full = np.full((2, 2), 7) # 2x2 array filled with 7
identity = np.eye(3)      # 3x3 Identity matrix
arange = np.arange(0, 10, 2) # Array from 0 to 10 with step 2
linspace = np.linspace(0, 1, 5) # 5 equally spaced points from 0 to 1
print('\n 2x3 array of zeros \n',zeros)
print('\n 3x3 array of ones\n',ones)
print('\n 2x2 array filled with 7\n',full)
print('\n 3x3 Identity matrix\n',identity)
print('\n Array from 0 to 10 with step 2\n',arange)
print('\n 5 equally spaced points from 0 to 1\n',linspace)



 2x3 array of zeros 
 [[0. 0. 0.]
 [0. 0. 0.]]

 3x3 array of ones
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

 2x2 array filled with 7
 [[7 7]
 [7 7]]

 3x3 Identity matrix
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

 Array from 0 to 10 with step 2
 [0 2 4 6 8]

 5 equally spaced points from 0 to 1
 [0.   0.25 0.5  0.75 1.  ]


In [23]:
# Random Arrays
random_uniform = np.random.rand(2, 3)  # Random values in [0, 1)
random_normal = np.random.randn(2, 3)  # Random values from normal distribution
random_int = np.random.randint(0, 10, (2, 2))  # Random integers in [0, 10)
print('\n Random values in [0, 1) \n',random_uniform)
print('\n Random values from normal distribution \n ',random_normal)
print('\n Random integers in [0, 10) \n ',random_int)


 Random values in [0, 1) 
 [[0.38794305 0.40898888 0.41813967]
 [0.94469189 0.94397193 0.01225869]]

 Random values from normal distribution 
  [[ 1.92679082  1.1523416  -0.41684816]
 [-1.87744047 -0.68714032 -0.59717432]]

 Random integers in [0, 10) 
  [[1 9]
 [1 8]]


In [26]:
# Reshaping Arrays
print('\n above 1d array \n ',array_1d)
reshaped = np.reshape(array_1d, (2, 2))  # Reshape to 2x2
flattened = array_2d.flatten()  # Flatten 2D to 1D
print('\n reshape to 2x2 \n ',reshaped)
print('\n flatten 2d to 1d \n',flattened)


 above 1d array 
  [1 2 3 4]

 reshape to 2x2 
  [[1 2]
 [3 4]]

 flatten 2d to 1d 
 [1 2 3 4]


In [30]:
# Stacking Arrays
vstack = np.vstack((array_1d, array_1d,array_1d))  # Vertical stack
hstack = np.hstack((array_1d, array_1d))  # Horizontal stack
print('\n vertical stack \n ',vstack)
print('\n horizontal stack \n',hstack)



 vertical stack 
  [[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]

 horizontal stack 
 [1 2 3 4 1 2 3 4]


In [38]:
# Splitting Arrays
split = np.split(array_1d, 2)  # Split array into 2 parts
print('\n after split \n',split)
print('\n new arrays are \n ',split[0],'\t and ',split[1])



 after split 
 [array([1, 2]), array([3, 4])]

 new arrays are 
  [1 2] 	 and  [3 4]


In [40]:
# Mathematical Operations
array = np.array([1, 2, 3, 4])
sum_result = np.sum(array)   # Sum of all elements
mean_result = np.mean(array) # Mean of elements
max_result = np.max(array)   # Maximum value
min_result = np.min(array)   # Minimum value
std_dev = np.std(array)      # Standard deviation
print('\n sum \t:',sum_result)
print('\n mean \t:',mean_result)
print('\n max value \t:',max_result)
print('\n min value \t:',min_result)
print('\n standard deviation \t:', std_dev)



 sum 	: 10

 mean 	: 2.5

 max value 	: 4

 min value 	: 1

 standard deviation 	: 1.118033988749895


In [42]:
# Element-wise Operations
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
addition = array1 + array2      # Element-wise addition
multiplication = array1 * array2 # Element-wise multiplication
dot_product = np.dot(array1, array2) # Dot product
print('\n element wise addition \t:',addition)
print('\n element wise multiplication \t:',multiplication)
print('\n dot product \t:',dot_product)



 element wise addition 	: [5 7 9]

 element wise multiplication 	: [ 4 10 18]

 dot product 	: 32


In [44]:
# Boolean Operations
bool_array = array > 2  # Element-wise comparison
any_true = np.any(bool_array)  # Check if any element is True
all_true = np.all(bool_array)  # Check if all elements are True

print('\n check if any element is true \t:',any_true)
print('\n check if alll elements are true \t:',all_true)


 check if any element is true 	: True

 check if alll elements are true 	: False


In [46]:
# Broadcasting
x = np.array([1, 2, 3])
y = np.array([[1], [2], [3]])
broadcasted_sum = x + y  # Add with broadcasting
print('\n add with broadcasting \t:',broadcasted_sum)



 add with broadcasting 	: [[2 3 4]
 [3 4 5]
 [4 5 6]]


In [48]:
# Fancy Indexing
fancy_indexed = array[[0, 2]]  # Access specific indices
print('\n access specific indices \t:',fancy_indexed)


 access specific indices 	: [1 3]


In [53]:

# Linear Algebra
matrix = np.array([[1, 2], [3, 4]])
transpose = np.transpose(matrix)    # Transpose of the matrix
inverse = np.linalg.inv(matrix)     # Inverse of the matrix
determinant = np.linalg.det(matrix) # Determinant

eigenvalues, eigenvectors = np.linalg.eig(matrix) # Eigenvalues and eigenvectors
print('\n matrix transpose\n:',transpose)
print('\n inverse of matrix \n:',inverse)
print('\n determinant \n:',determinant)
print('\n eigenvalues \t:',eigenvalues)
print('\n eigenvectors \n:',eigenvectors)


 matrix transpose
: [[1 3]
 [2 4]]

 inverse of matrix 
: [[-2.   1. ]
 [ 1.5 -0.5]]

 determinant 
: -2.0000000000000004

 eigenvalues 	: [-0.37228132  5.37228132]

 eigenvectors 
: [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [57]:
# Performance Optimization with Numba
from numba import jit

@jit
def fast_function(x):
    return np.sum(x ** 2)


print(fast_function(np.array([4,2,3])))


29


In [58]:
# -------------------------- MORE ADVANCED USAGE --------------------------


In [60]:
# Structured Arrays
structured_array = np.array([(1, 'santosh', 21), (2, 'nabin', 21)],
                             dtype=[('id', 'i4'), ('name', 'U10'), ('age', 'i4')])
print(structured_array['name'])  # Access 'name' field


['santosh' 'nabin']


In [63]:
# Advanced Linear Algebra
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])

matrix_multiplication = np.matmul(matrix_a, matrix_b)  # Matrix multiplication
svd = np.linalg.svd(matrix_a)  # Singular Value Decomposition

print('\n matrix multiplication \n:',matrix_multiplication)
print('\n singular value decomposition \n:',svd)



 matrix multiplication 
: [[19 22]
 [43 50]]

 singular value decomposition 
: SVDResult(U=array([[-0.40455358, -0.9145143 ],
       [-0.9145143 ,  0.40455358]]), S=array([5.4649857 , 0.36596619]), Vh=array([[-0.57604844, -0.81741556],
       [ 0.81741556, -0.57604844]]))


In [65]:
# Advanced Random Sampling
random_choice = np.random.choice(array, size=3, replace=False)  # Random sampling without replacement
print('\n random smapling without replacement\t:',random_choice)


 random smapling without replacement	: [4 2 3]


In [66]:
# Advanced Broadcasting
array3 = np.array([1, 2, 3])
array4 = np.array([[1], [2], [3]])
broadcasted_result = array3 * array4  # Multiply with broadcasting
print('\n multiply with broadcasting \t',broadcasted_result)



 multiply with broadcasting 	 [[1 2 3]
 [2 4 6]
 [3 6 9]]


In [67]:
# Memory Management
shared_memory = np.empty((1000, 1000), dtype=np.float64)
np.copyto(shared_memory, np.random.rand(1000, 1000))  # Efficient copying


In [68]:
# Custom Universal Functions (ufuncs)
def custom_function(x, y):
    return x ** 2 + y ** 2

custom_ufunc = np.frompyfunc(custom_function, 2, 1)
result = custom_ufunc(array1, array2)
print(result)


[17 29 45]


In [70]:
# Advanced Masking with np.where
condition = array > 2
conditional_result = np.where(condition, array, -1)  # Replace elements based on condition
print('\n replace elements based on codition \n:',conditional_result)


 replace elements based on codition 
: [-1 -1  3  4]


In [72]:
# Multidimensional Indexing with np.ix_
row_indices = np.array([0, 1])
col_indices = np.array([1, 0])
indexed_elements = matrix[np.ix_(row_indices, col_indices)]
print('\n multidimensonal indexing \n:',indexed_elements)


 multidimensonal indexing 
: [[2 1]
 [4 3]]


In [73]:
# High-Performance Computations
large_array = np.random.rand(1000000)
sum_large_array = np.sum(large_array)  # Efficient summation using optimized C backend
print('\nefficient summation using optimized c backend:',sum_large_array)


efficient summation using optimized c backend: 499654.19446033216


In [74]:
# Memory-Mapped Files
mmap_array = np.memmap("large_file.dat", dtype='float32', mode='w+', shape=(1000, 1000))
mmap_array[:] = np.random.rand(1000, 1000)
mmap_array.flush()  # Ensure changes are written to disk


In [75]:
# Advanced Sorting
sorted_array = np.sort(array)  # Sort along an axis
sorted_indices = np.argsort(array)  # Indices of sorted elements
print('\n indices of sorted elements \n :',sorted_indices)


 indices of sorted elements 
 : [0 1 2 3]


In [77]:
# Advanced Fourier Transforms
from numpy.fft import fft, ifft
signal = np.sin(np.linspace(0, 2 * np.pi, 100))
signal_fft = fft(signal)  # Compute FFT
signal_reconstructed = ifft(signal_fft)  # Inverse FFT
print('\n fft:',signal_fft)
print('\n inverse of fft \n',signal_reconstructed)


 fft: [-6.93889390e-17+0.00000000e+00j  1.56237833e+00-4.97156846e+01j
 -4.25850363e-02+6.76869769e-01j -3.57787605e-02+3.78499750e-01j
 -3.38833476e-02+2.68214314e-01j -3.30724162e-02+2.08811018e-01j
 -3.26479847e-02+1.71146729e-01j -3.23973043e-02+1.44937208e-01j
 -3.22366676e-02+1.25553531e-01j -3.21274678e-02+1.10583469e-01j
 -3.20498259e-02+9.86392214e-02j -3.19926363e-02+8.88629658e-02j
 -3.19492912e-02+8.06946984e-02j -3.19156560e-02+7.37527294e-02j
 -3.18890343e-02+6.77676474e-02j -3.18676064e-02+6.25436991e-02j
 -3.18501078e-02+5.79351310e-02j -3.18356374e-02+5.38311230e-02j
 -3.18235390e-02+5.01458735e-02j -3.18133256e-02+4.68118870e-02j
 -3.18046293e-02+4.37753167e-02j -3.17971683e-02+4.09926624e-02j
 -3.17907237e-02+3.84283836e-02j -3.17851234e-02+3.60531455e-02j
 -3.17802305e-02+3.38425081e-02j -3.17759351e-02+3.17759351e-02j
 -3.17721482e-02+2.98360331e-02j -3.17687971e-02+2.80079622e-02j
 -3.17658219e-02+2.62789733e-02j -3.17631731e-02+2.46380426e-02j
 -3.17608093e-02+2

In [78]:
# Parallel Processing with Numpy
from multiprocessing import Pool

def parallel_sum(arr):
    return np.sum(arr)

if __name__ == "__main__":
    data = np.random.rand(1000000).reshape(100, 10000)
    with Pool(4) as p:
        results = p.map(parallel_sum, [data[i] for i in range(data.shape[0])])
    print(f"Parallel Sum: {np.sum(results)}")


Parallel Sum: 499626.6078994466
